create table if not exists job_execution (
  id bigint generated by default as identity primary key,
  job_id varchar(64) not null,
  job_type varchar(64) not null,
  station_scope varchar(128),
  idempotency_key varchar(128) not null,
  attempt integer not null,
  status varchar(32) not null,
  started_at timestamp,
  finished_at timestamp,
  error_message varchar(512),
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);

create unique index if not exists uk_job_execution_idempotency_key
  on job_execution(idempotency_key);

create index if not exists idx_job_execution_job_type_status
  on job_execution(job_type, status);
