create table if not exists users_account_metadata (
    id bigint generated by default as identity primary key,
    tenant_id varchar(64) not null,
    account_id varchar(64) not null,
    operator_id varchar(64),
    customer_id varchar(64),
    identity_state varchar(32) not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint uq_users_account_metadata_tenant_account unique (tenant_id, account_id)
);

create table if not exists billing_session_aggregate (
    id bigint generated by default as identity primary key,
    session_id varchar(128) not null,
    station_id varchar(64) not null,
    tenant_id varchar(64) not null,
    account_id varchar(64) not null,
    rated_wh bigint not null,
    rated_amount numeric(12,4) not null,
    currency varchar(8) not null,
    invoice_ready boolean not null default false,
    rated_at timestamp with time zone not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint uq_billing_session_aggregate_session unique (session_id),
    constraint fk_billing_session_aggregate_station_id
        foreign key (station_id) references charging_station (station_id)
);

create index if not exists idx_billing_session_aggregate_tenant_account
    on billing_session_aggregate (tenant_id, account_id);

create table if not exists firmware_version_inventory (
    id bigint generated by default as identity primary key,
    tenant_id varchar(64) not null,
    version varchar(64) not null,
    release_channel varchar(32) not null,
    rollout_notes varchar(1024),
    created_at timestamp with time zone not null default now(),
    constraint uq_firmware_version_inventory_tenant_version unique (tenant_id, version)
);

create table if not exists firmware_rollout_campaign (
    id bigint generated by default as identity primary key,
    campaign_id varchar(64) not null,
    tenant_id varchar(64) not null,
    target_version varchar(64) not null,
    started_at timestamp with time zone not null default now(),
    status varchar(32) not null,
    created_at timestamp with time zone not null default now(),
    constraint uq_firmware_rollout_campaign_campaign unique (campaign_id),
    constraint fk_firmware_rollout_campaign_target_version
        foreign key (tenant_id, target_version)
            references firmware_version_inventory (tenant_id, version)
);

create table if not exists firmware_rollout_status (
    id bigint generated by default as identity primary key,
    station_id varchar(64) not null,
    tenant_id varchar(64) not null,
    campaign_id varchar(64) not null,
    target_version varchar(64) not null,
    rollout_state varchar(32) not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint uq_firmware_rollout_status_campaign_station unique (campaign_id, station_id),
    constraint fk_firmware_rollout_status_station
        foreign key (station_id) references charging_station (station_id),
    constraint fk_firmware_rollout_status_campaign
        foreign key (campaign_id) references firmware_rollout_campaign (campaign_id)
);

create index if not exists idx_firmware_rollout_status_tenant
    on firmware_rollout_status (tenant_id, updated_at desc);
